Graceful recovery

diff --git a/patching/patch_wls.yaml b/patching/patch_wls.yaml
--- a/patching/patch_wls.yaml
+++ b/patching/patch_wls.yaml
@@ -130,14 +130,16 @@
             
               # Remove backup file
               rm {{ inventory_hostname }}_{{ ansible_date_time.iso8601 | replace(':','-') }}.tar.gz
-            
+              
+              echo "Backup is rolled back and backup is deleted afterwards" >&2
+              echo "Failed to patch the weblogic server. Please check that there is enough disk space, memory (Heap), and check logs!" >&2
               exit 1
             }
                         
             export ORACLE_HOME={{ item }}
             export OPATCH_JRE_MEMORY_OPTIONS='-Xmx5172m'
             
-            {{ upgrade_home }}/{{ weblogic_patch_spb_directory }}/tools/spbat/generic/SPBAT/spbat.sh -phase apply -oracle_home {{ item }} || rollback
+            {{ upgrade_home }}/{{ weblogic_patch_spb_directory }}/tools/spbat/generic/SPBAT/spbat.sh -silent -phase apply -oracle_home {{ item }} || rollback
           loop: "{{ oracle_home }}"
           ignore_errors: yes
 
